# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Manga.create(title:"EightySix", availability:"Available",volumeNum:1,owner:"Liam O'Driscoll",borrower:nil,  value:5)
Manga.create(title:"EightySix",availability:"Available",volumeNum:2,owner:"Liam O'Driscoll",borrower:nil,  value:5)
Manga.create(title:"EightySix",availability:"Borrowed",volumeNum:3, owner:"Liam O'Driscoll",borrower:"LO#3323",value:5)
Manga.create(title:"EightySix",availability:"Available",volumeNum:4, owner:"Liam O'Driscoll",borrower:nil,  value:5)
Manga.create(title:"Kaguya-sama: Love Is War",availability:"Available",volumeNum:1,owner:"Liam O",borrower:nil,  value:5)
Manga.create(title:"Kaguya-sama: Love Is War",availability:"Available",volumeNum:2,owner:"Liam O'Driscoll",borrower:nil,  value:5)
Manga.create(title:"Kaguya-sama: Love Is War",availability:"Available",volumeNum:3, owner:"Liam O'Driscoll",borrower:nil,  value:5)
Manga.create(title:"One Punch Man",availability:"Available",volumeNum:1,owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"One Punch Man",availability:"Available",volumeNum:2,owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"One Punch Man",availability:"Available",volumeNum:3, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"One Punch Man",availability:"Available",volumeNum:4, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"One Punch Man",availability:"Available",volumeNum:5, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"One Punch Man",availability:"Available",volumeNum:6, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Borrowed",volumeNum:1,owner:"SAMsoc",borrower:"AJ#2586",value:5)
Manga.create(title:"The Promised Neverland",availability:"Borrowed",volumeNum:2,owner:"SAMsoc",borrower:"AJ#2586",value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:3, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:4, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:5, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:6, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:7, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:8, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:9, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:10, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"The Promised Neverland",availability:"Available",volumeNum:11,owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"Goodnight PunPun",availability:"Borrowed",volumeNum:1,owner:"SAMsoc",borrower:"GB#9174",value:10)
Manga.create(title:"Goodnight PunPun",availability:"Borrowed",volumeNum:2,owner:"SAMsoc",borrower:"GB#9174",value:10)
Manga.create(title:"Goodnight PunPun",availability:"Borrowed",volumeNum:3, owner:"SAMsoc",borrower:"GB#9174",value:10)
Manga.create(title:"Goodnight PunPun",availability:"Borrowed",volumeNum:4, owner:"SAMsoc",borrower:"PE#4265",value:10)
Manga.create(title:"Goodnight PunPun",availability:"Borrowed",volumeNum:5, owner:"SAMsoc",borrower:"SA#0001",value:10)
Manga.create(title:"Goodnight PunPun",availability:"Borrowed",volumeNum:6, owner:"SAMsoc",borrower:"SA#0001",value:10)
Manga.create(title:"Goodnight PunPun",availability:"Borrowed",volumeNum:7, owner:"SAMsoc",borrower:"SA#0001",value:10)
Manga.create(title:"The Promised Neverland",availability:"Borrowed",volumeNum:1,owner:"SAMsoc",borrower:"AJ#2586",value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Borrowed",volumeNum:1,owner:"SAMsoc",borrower:"SP#4143",value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Borrowed",volumeNum:2,owner:"SAMsoc",borrower:"SP#4143",value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Available",volumeNum:3, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Available",volumeNum:4, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Borrowed",volumeNum:5, owner:"SAMsoc",borrower:"AD#8395",value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Borrowed",volumeNum:6, owner:"SAMsoc",borrower:"AD#8395",value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Available",volumeNum:7, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Available",volumeNum:8, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Available",volumeNum:9, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Available",volumeNum:10, owner:"SAMsoc",borrower:nil,  value:5)
Manga.create(title:"Tokyo Ghoul",availability:"Available",volumeNum:11,owner:"SAMsoc",borrower:nil,  value:5)
